import type { TeXOptions } from '../../src';
import type {
	FunctionSolverOptions as AdvancedFunctionSolverOptions,
	GroebnerBasisOptions,
	GroebnerStats,
	MonomialOrder,
	RationalSolution,
	Root as AdvancedRoot,
	RootFindingMethod,
} from '../../src/api/advanced';
import type {
	EvalInputType,
	Ordering,
	PowersObject,
	PolyType,
	VariableFrequency,
} from '../../src/api/algebra';
import type {
	AssumptionComparison,
	AssumptionValue,
	Bound,
	ParsedAssumption,
} from '../../src/api/assumptions';
import type { LimitDir } from '../../src/api/calculus';
import type {
	ElementsSortType,
	ExpressionInput,
	JsFunction as CoreJsFunction,
	NerdamerInput,
	OptionValue as CoreOptionValue,
	OptionsObject as CoreOptionsObject,
	ParserConstants as CoreParserConstants,
	ParserEntity,
	ParserValuesObject as CoreParserValuesObject,
	StructuredEntityType as CoreStructuredEntityType,
} from '../../src/api/core';
import type {
	DebugCollection,
	DebugDictionary,
	DebugDictionaryEntry,
	DebugEntity,
	DebugEquation,
	DebugExpression,
	DebugMatrix,
	DebugPolynomial,
	DebugScope,
	DebugScopeItem,
	DebugTerm,
	DebugToken,
	DebugValuesSet,
	DebugVector,
	ParseInspection,
} from '../../src/api/debug';
import type {
	BinaryArithmeticOperation,
	ComparisonOperation,
	JsFunction as ParserJsFunction,
	Language,
	Operation,
	Operator,
	OperatorAction,
	OperatorDefinition,
	OptionValue as ParserOptionValue,
	OptionsObject as ParserOptionsObject,
	ParserAPI,
	ParserConstants as ParserParserConstants,
	ParserValuesObject as ParserParserValuesObject,
	PostFixFunction,
	PreFixFunction,
	SettingsType,
} from '../../src/api/parser';
import type {
	FunctionSolverOptions as SolveFunctionSolverOptions,
	MultivariateSolverOptions,
	Root as SolveRoot,
	SolutionForm,
	SolutionsType,
} from '../../src/api/solve';
import type { StructuredEntityType as StructuresStructuredEntityType } from '../../src/api/structures';

type PublicTypeContract = [
	TeXOptions,
	ElementsSortType,
	ExpressionInput,
	CoreJsFunction,
	NerdamerInput,
	CoreOptionValue,
	CoreOptionsObject,
	CoreParserConstants,
	ParserEntity,
	CoreParserValuesObject,
	CoreStructuredEntityType,
	EvalInputType,
	Ordering,
	PowersObject,
	PolyType,
	VariableFrequency,
	LimitDir,
	SolveFunctionSolverOptions,
	MultivariateSolverOptions,
	SolveRoot,
	SolutionForm,
	SolutionsType,
	StructuresStructuredEntityType,
	AssumptionComparison,
	AssumptionValue,
	Bound,
	ParsedAssumption,
	BinaryArithmeticOperation,
	ComparisonOperation,
	ParserJsFunction,
	Language,
	Operation,
	Operator,
	OperatorAction,
	OperatorDefinition,
	ParserOptionValue,
	ParserOptionsObject,
	ParserAPI,
	ParserParserConstants,
	ParserParserValuesObject,
	PostFixFunction,
	PreFixFunction,
	SettingsType,
	AdvancedFunctionSolverOptions,
	GroebnerBasisOptions,
	GroebnerStats,
	MonomialOrder,
	RationalSolution,
	AdvancedRoot,
	RootFindingMethod,
	DebugCollection,
	DebugDictionary,
	DebugDictionaryEntry,
	DebugEntity,
	DebugEquation,
	DebugExpression,
	DebugMatrix,
	DebugPolynomial,
	DebugScope,
	DebugScopeItem,
	DebugTerm,
	DebugToken,
	DebugValuesSet,
	DebugVector,
	ParseInspection,
];

describe('public type API contract', () => {
	it('keeps every intentional public type importable', () => {
		const contractIsCompiled: PublicTypeContract | undefined = undefined;
		expect(contractIsCompiled).toBeUndefined();
	});
});
