import { mathFunctionRegistry, systemFunction } from '../core/dispatch';
import {
	DIRAC,
	DOUBLE_FACTORIAL,
	FACTORIAL,
	HEAVISIDE,
	LI,
} from '../core/classes/parser/constants';
import { numeric } from '../core/classes/parser/scripting/evaluate';
import { expand } from '../core/functions/expand/expand';
import { subst } from '../core/functions/subst';
import { hypot, line } from './geometry';
import {
	sqrt,
	cbrt,
	factorial,
	fibonacci,
	abs,
	erf,
	erfc,
	log,
	log10,
	exp,
	gamma,
	gammaIncomplete,
	gammaIncompleteLower,
	dirac,
	heaviside,
	step,
	rect,
	tri,
	radians,
	degrees,
	doubleFactorial,
	round,
	floor,
	ceiling,
	mod,
	modInv,
	parens,
	sign,
	sinc,
	Shi,
	Si,
	Chi,
	Ci,
	Ei,
	Li,
	contains,
	max,
	min,
	nthroot,
	scientific,
} from './math';
import {
	cos,
	sin,
	tan,
	sec,
	csc,
	cot,
	acos,
	asin,
	atan,
	asec,
	acsc,
	acot,
	atan2,
	cosh,
	sinh,
	tanh,
	sech,
	csch,
	coth,
	acosh,
	asinh,
	atanh,
	asech,
	acsch,
	acoth,
} from './trig';
import { trunc } from './trunc';
import { continuedFraction, count, isprime, size } from './utils';

export function loadMathFunctions() {
	Object.assign(mathFunctionRegistry, {
		cos: systemFunction({ fn: cos, minArgs: 1, maxArgs: 1, distElWise: true }),
		sin: systemFunction({ fn: sin, minArgs: 1, maxArgs: 1, distElWise: true }),
		tan: systemFunction({ fn: tan, minArgs: 1, maxArgs: 1, distElWise: true }),
		sec: systemFunction({ fn: sec, minArgs: 1, maxArgs: 1, distElWise: true }),
		csc: systemFunction({ fn: csc, minArgs: 1, maxArgs: 1, distElWise: true }),
		cot: systemFunction({ fn: cot, minArgs: 1, maxArgs: 1, distElWise: true }),
		acos: systemFunction({ fn: acos, minArgs: 1, maxArgs: 1, distElWise: true }),
		asin: systemFunction({ fn: asin, minArgs: 1, maxArgs: 1, distElWise: true }),
		atan: systemFunction({ fn: atan, minArgs: 1, maxArgs: 1, distElWise: true }),
		asec: systemFunction({ fn: asec, minArgs: 1, maxArgs: 1, distElWise: true }),
		acsc: systemFunction({ fn: acsc, minArgs: 1, maxArgs: 1, distElWise: true }),
		acot: systemFunction({ fn: acot, minArgs: 1, maxArgs: 1, distElWise: true }),
		atan2: systemFunction({ fn: atan2, minArgs: 2, maxArgs: 2, distElWise: true }),
		cosh: systemFunction({ fn: cosh, minArgs: 1, maxArgs: 1, distElWise: true }),
		sinh: systemFunction({ fn: sinh, minArgs: 1, maxArgs: 1, distElWise: true }),
		tanh: systemFunction({ fn: tanh, minArgs: 1, maxArgs: 1, distElWise: true }),
		sech: systemFunction({ fn: sech, minArgs: 1, maxArgs: 1, distElWise: true }),
		csch: systemFunction({ fn: csch, minArgs: 1, maxArgs: 1, distElWise: true }),
		coth: systemFunction({ fn: coth, minArgs: 1, maxArgs: 1, distElWise: true }),
		acosh: systemFunction({ fn: acosh, minArgs: 1, maxArgs: 1, distElWise: true }),
		asinh: systemFunction({ fn: asinh, minArgs: 1, maxArgs: 1, distElWise: true }),
		atanh: systemFunction({ fn: atanh, minArgs: 1, maxArgs: 1, distElWise: true }),
		asech: systemFunction({ fn: asech, minArgs: 1, maxArgs: 1, distElWise: true }),
		acsch: systemFunction({ fn: acsch, minArgs: 1, maxArgs: 1, distElWise: true }),
		acoth: systemFunction({ fn: acoth, minArgs: 1, maxArgs: 1, distElWise: true }),

		line: systemFunction({ fn: line, minArgs: 2, maxArgs: 3, distElWise: false }),
		abs: systemFunction({ fn: abs, minArgs: 1, maxArgs: 1, distElWise: true }),
		sqrt: systemFunction({ fn: sqrt, minArgs: 1, maxArgs: 1, distElWise: true }),
		nthroot: systemFunction({ fn: nthroot, minArgs: 2, maxArgs: 2, distElWise: true }),
		cbrt: systemFunction({ fn: cbrt, minArgs: 1, maxArgs: 1, distElWise: true }),
		subst: systemFunction({ fn: subst, minArgs: 3, maxArgs: 3, distElWise: true }),
		log: systemFunction({ fn: log, minArgs: 1, maxArgs: 2, distElWise: true }),
		log10: systemFunction({ fn: log10, minArgs: 1, maxArgs: 1, distElWise: true }),
		radians: systemFunction({ fn: radians, minArgs: 1, maxArgs: 1, distElWise: true }),
		degrees: systemFunction({ fn: degrees, minArgs: 1, maxArgs: 1, distElWise: true }),
		exp: systemFunction({ fn: exp, minArgs: 1, maxArgs: 1, distElWise: true }),
		erf: systemFunction({ fn: erf, minArgs: 1, maxArgs: 1, distElWise: true }),
		erfc: systemFunction({ fn: erfc, minArgs: 1, maxArgs: 1, distElWise: true }),
		gamma: systemFunction({ fn: gamma, minArgs: 1, maxArgs: 1, distElWise: true }),
		gamma_incomplete: systemFunction({ fn: gammaIncomplete, minArgs: 2, maxArgs: 2, distElWise: true }),
		gamma_incomplete_lower: systemFunction({ fn: gammaIncompleteLower, minArgs: 2, maxArgs: 2, distElWise: true }),
		[DIRAC]: systemFunction({ fn: dirac, minArgs: 1, maxArgs: 1, distElWise: true }),
		[HEAVISIDE]: systemFunction({ fn: heaviside, minArgs: 1, maxArgs: 1, distElWise: true }),
		step: systemFunction({ fn: step, minArgs: 1, maxArgs: 1, distElWise: true }),
		rect: systemFunction({ fn: rect, minArgs: 1, maxArgs: 1, distElWise: true }),
		tri: systemFunction({ fn: tri, minArgs: 1, maxArgs: 1, distElWise: true }),
		continued_fraction: systemFunction({ fn: continuedFraction, minArgs: 1, maxArgs: 2, distElWise: false }),
		scientific: systemFunction({ fn: scientific, minArgs: 1, maxArgs: 2, distElWise: true }),
		hypot: systemFunction({ fn: hypot, minArgs: 2, maxArgs: 2, distElWise: true }),
		[FACTORIAL]: systemFunction({ fn: factorial, minArgs: 1, maxArgs: 1, distElWise: true }),
		factorial: systemFunction({ fn: factorial, minArgs: 1, maxArgs: 1, distElWise: true }),
		[DOUBLE_FACTORIAL]: systemFunction({ fn: doubleFactorial, minArgs: 1, maxArgs: 1, distElWise: true }),
		expand: systemFunction({ fn: expand, minArgs: 1, maxArgs: 1, distElWise: true }),
		numeric: systemFunction({
			fn: numeric,
			minArgs: 1,
			maxArgs: 2,
			equationArgs: [0],
			distElWise: false,
			deferArguments: true,
		}),
		round: systemFunction({ fn: round, minArgs: 1, maxArgs: 2, distElWise: true }),
		sign: systemFunction({ fn: sign, minArgs: 1, maxArgs: 1, distElWise: true }),
		floor: systemFunction({ fn: floor, minArgs: 1, maxArgs: 1, distElWise: true }),
		ceil: systemFunction({ fn: ceiling, minArgs: 1, maxArgs: 1, distElWise: true }),
		ceiling: systemFunction({ fn: ceiling, minArgs: 1, maxArgs: 1, distElWise: true }),
		trunc: systemFunction({ fn: trunc, minArgs: 1, maxArgs: 1, distElWise: true }),
		mod: systemFunction({ fn: mod, minArgs: 2, maxArgs: 2, distElWise: true }),
		modinv: systemFunction({ fn: modInv, minArgs: 2, maxArgs: 2, distElWise: true }),
		parens: systemFunction({ fn: parens, minArgs: 1, maxArgs: 1, distElWise: true }),
		count: systemFunction({ fn: count, minArgs: 1, maxArgs: 1, distElWise: false }),
		size: systemFunction({ fn: size, minArgs: 1, maxArgs: 1, distElWise: false }),
		contains: systemFunction({ fn: contains, minArgs: 2, maxArgs: 2, distElWise: false }),
		max: systemFunction({ fn: max, minArgs: 2, maxArgs: -1, distElWise: true }),
		min: systemFunction({ fn: min, minArgs: 2, maxArgs: -1, distElWise: true }),

		isprime: systemFunction({ fn: isprime, minArgs: 1, maxArgs: 1, distElWise: true }),
		fib: systemFunction({ fn: fibonacci, minArgs: 1, maxArgs: 1, distElWise: true }),
		sinc: systemFunction({ fn: sinc, minArgs: 1, maxArgs: 1, distElWise: true }),
		Shi: systemFunction({ fn: Shi, minArgs: 1, maxArgs: 1, distElWise: true }),
		Si: systemFunction({ fn: Si, minArgs: 1, maxArgs: 1, distElWise: true }),
		Chi: systemFunction({ fn: Chi, minArgs: 1, maxArgs: 1, distElWise: true }),
		Ci: systemFunction({ fn: Ci, minArgs: 1, maxArgs: 1, distElWise: true }),
		Ei: systemFunction({ fn: Ei, minArgs: 1, maxArgs: 1, distElWise: true }),
		[LI]: systemFunction({ fn: Li, minArgs: 1, maxArgs: 1, distElWise: true }),
	});
}
